"""Application identity constants (Section 10.2).

The app name is not decided yet - code never hard-codes it, it reads ``APP_NAME``
(env-overridable). The attribution strings are fixed and are NOT translated.
"""

from __future__ import annotations

import os

APP_NAME: str = os.environ.get("APP_NAME", "KNSB Motor Designer")
APP_AUTHOR: str = "PARS Rocketry Team"
APP_AUTHOR_URL: str = "https://github.com/asebyrm"

ATTRIBUTION_LINE: str = f"Generated by {APP_NAME} - by {APP_AUTHOR} - github.com/asebyrm"
DISCLAIMER_SHORT: str = "NOT FLIGHT CERTIFIED - amateur research motor, simulated data only"
